# Generated by Django 2.2.6 on 2019-12-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20191201_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=9, verbose_name='Tax Number'),
            preserve_default=False,
        ),
    ]
