# Generated by Django 2.2.6 on 2019-12-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_company_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tax Number'),
        ),
    ]
