# Generated by Django 2.2.6 on 2019-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20191201_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(unique=True, verbose_name='Tax Number'),
        ),
    ]
